apiVersion: apps/v1
kind: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: vladandreifinalproject.azurecr.io/imaginetest1:latest  
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-secret  
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer  
  selector:
    app: flask
  ports:
  - port: 5000  
    targetPort: 5000  
    nodePort: 30000   